[project]
name = "comfyui_ipadapter_plus_fork"
description = "Updated version of IPAdapter Plus.\nComfyUI reference implementation for the IPAdapter models. The IPAdapter are very powerful models for image conditioning. The style and composition of a reference can be easily transferred to the generation. Think of it as a 1-image lora."
version = "3.0.0"
license = "GPL-3.0 license"

[project.urls]
Repository = "https://github.com/pamparamm/ComfyUI_IPAdapter_plus"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "pamparamm"
DisplayName = "ComfyUI_IPAdapter_plus_fork"
Icon = ""

[tool.ruff]
lint.select = [
    "N805", # invalid-first-argument-name-for-method
    "S307", # suspicious-eval-usage
    "S102", # exec
    "T",    # print-usage
    "W",
    # The "F" series in Ruff stands for "Pyflakes" rules, which catch various Python syntax errors and undefined names.
    # See all rules here: https://docs.astral.sh/ruff/rules/#pyflakes-f
    "F",
    "I",
]
